datasets:
  default: /voyager/datasets
  cifar10_1: /voyager/datasets/cifar-10-1
  fake_mnist: /voyager/datasets/fake_mnist
  uci_heart: /voyager/datasets/UCI
  camelyon_quantized: /voyager/datasets/camelyon17
  celeb: /voyager/datasets/CelebA
  imagenet1k: /voyager/datasets/ImageNet1k
  imagenetV2: /voyager/datasets/imagenet_v2/imagenetv2-threshold0.7-format-val
checkpoint_path: /voyager/projects/tomginsberg/shiftdynamics/checkpoints